# Generated by Django 4.0.1 on 2022-01-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=100)),
                ('smark1', models.CharField(default='0', max_length=100)),
                ('smark2', models.CharField(default='0', max_length=15)),
                ('smark3', models.CharField(default='0', max_length=15)),
                ('scomment', models.CharField(default='Nil', max_length=15)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
